baseURL = "/"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "The Valley of the Sun .NET User Groups"
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 4
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 5
[params]
address = "PO Box 63262 Phoenix AZ 85082"
author = "Barry S. Stahl"
copyright = "Copyrighht &copy; 2021"
description = "This is meta description"
email = "valleyofthesundotnet@bsstahl.com"
google_analitycs_id = ""
home = "Home"
logo = "images/logo.svg"
phone = ""
theme_color = "#41228e"
[params.contact]
enable = true
form_action = "#"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
preloader = ""
[[params.social]]
URL = "https://www.meetup.com/nwvdnug/"
icon = "ti-arrow-top-left"
[[params.social]]
URL = "https://www.meetup.com/sevdnug/"
icon = "ti-arrow-bottom-right"
[[params.social]]
URL = "#"
icon = "ti-dribbble"
[[params.social]]
URL = "#"
icon = "ti-twitter-alt"
